version: '3'
services:
  rtsp2hls:
    image: rtsp2hls 
    ports:
      - "7123:7123"
      - "4123:4123"
  canvas_handler:
     image: canvas_handler
     ports:
      - "7000:7000"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'

